name: e2e
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: v1.53.2
          args: --timeout 5m
          working-directory: e2e/interchaintest
  build:
    strategy:
      matrix:
        test:
          - TestContractInstantiate
    name: ${{ matrix.test }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install cargo-run-script
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-run-script
      - name: Build Optimized Contracts
        run: |
          docker run --rm -v "$(pwd)":/code \
            --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
            --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
            cosmwasm/optimizer:0.15.0
      - name: Build Ica Controller Contract with Docker
        run: |
          cd third_party/cw-ica-controller
          docker run --rm -v "$(pwd)":/code \
            --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
            --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
            cosmwasm/optimizer:0.15.0
          cp artifacts/cw_ica_controller.wasm ../../artifacts/
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true
          cache-dependency-path: |
             e2e/interchaintest/go.sum
      - name: TestContract
        run: |
          cd e2e/interchaintest
          go test -v . -run TestWithContractTestSuite -testify.m ${{ matrix.test }}
